// Build-time VERSION generator.
//
// Reads the package's version field out of package.json and writes a tiny
// src/version.ts module exporting `VERSION`. npm runs this as a `prebuild`
// step so src/version.ts exists by the time `tsc` reads it.
//
// Why this exists: src/index.ts used to hand-duplicate the version string,
// and the two would drift. The single source of truth is package.json, and
// every build regenerates src/version.ts from it. The generated file is
// committed-friendly (it has the same byte content on every build at the
// same version) and is intentionally checked into git so that `tsc` can
// run with `--noEmit` without first invoking `npm run build`.
//
// IMPORTANT: this script must remain idempotent at a given version — a
// second run with the same package.json version must produce the same
// src/version.ts byte-for-byte, so the file can be committed.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(here, '..', 'package.json');
const outPath = join(here, '..', 'src', 'version.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = pkg.version;
if (typeof version !== 'string' || !/^\d+\.\d+\.\d+/.test(version)) {
  console.error(
    `build-version: package.json "version" must be a SemVer string, got ${JSON.stringify(version)}`,
  );
  process.exit(1);
}

const banner =
  '// AUTO-GENERATED by scripts/build-version.mjs — do not edit by hand.\n' +
  '// Source of truth: packages/elenwatch/package.json `version` field.\n' +
  '// Regenerate via `npm run prebuild` (runs before `npm run build`).\n' +
  '\n';
const body = `export const VERSION = ${`'${version}'`};\n`;
const out = banner + body;

const prev = existsSync(outPath)
  ? readFileSync(outPath, 'utf8')
  : undefined;
if (prev !== out) {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, out);
  console.log(
    `build-version: wrote src/version.ts with VERSION=${JSON.stringify(version)}`,
  );
} else {
  console.log(
    `build-version: src/version.ts already up to date at VERSION=${JSON.stringify(version)}`,
  );
}
