// AUTO-GENERATED by scripts/build-version.mjs — do not edit by hand.
// Source of truth: packages/elenwatch/package.json `version` field.
// Regenerate via `npm run prebuild` (runs before `npm run build`).

export const VERSION = '0.2.1';
